### ISSUE TITLE
Cross entropy loss is divided by the number of classes and not the batch size 

### ISSUE THREAD

**Issue by cDenius** [cirKITers/masKIT#34]
In the current cross entropy implementation, the loss value is [divided by N](https://github.com/cirKITers/masKIT/blob/f246fac0f051bcd964e39098ac70613496269f93/maskit/utils.py#L21). In principle, this should be the batch size. But since we are working with a batch size of one and thus call the function with a one-dimensional array, we are currently dividing by the number of classes which makes no sense at all. 

Deleting the division would solve the problem for batch size one (= dividing by one). But to support different batch sizes in the future, a more sophisticated solution would be nice.

**Comment by eileen-kuehn** [comment]
@all-contributors please add @cDenius for bug
