### ISSUE TITLE
A non existing class can be the circuit output for the iris dataset during testing

### ISSUE THREAD

**Issue by cDenius** [cirKITers/masKIT#36]
During testing of a model trained on the iris dataset, the predicted class should be the highest circuit output for 00, 01, and 10. Currently, the non existing class 11 could get the highest value and would be predicted. 

[See here](https://github.com/cirKITers/masKIT/blob/f246fac0f051bcd964e39098ac70613496269f93/main.py#L223)

**Comment by eileen-kuehn** [comment]
I am currently struggling a bit with the interpretation of an event where a maximum is recognised for a `11`. Does this mean, that the circuit did learn something wrong? So is it ok to only look at the subspace `00`-`10` and completely ignore the remaining states? Or can we just throw away those result?

Further I am thinking about generalising the number of classes to our train and test methods. As those things are strictly coupled to training, i.e. definition of loss and measurement we might simply input the states to evaluate as an iterable. At least this might be the most simple solution at the moment.

**Comment by cDenius** [comment]
For a classical neural network I would say:

The network is not trained for the ```11``` output so it is just an arbitrary output with no meaning. Therefore its value can be randomly bigger than every class prediction. 

But for a circuit I'm actually not sure because of entanglement. Eg. I could imagine that a high value for ```11``` correlates with the class ```10``` because the first bit is only one for this class and not for ```00``` and ```01```.

**Comment by eileen-kuehn** [comment]
> But for a circuit I'm actually not sure because of entanglement. Eg. I could imagine that a high value for `11` correlates with the class `10` because the first bit is only one for this class and not for `00` and `01`.

Good food for thought... I also thought about qubits tending to go back to ground state. But in case we are on a simulator, we don't care. Otherwise one might even consider explicitly picking specific states and therefore ignoring others as they might be more error-prone. Hmmm 🧐

**Comment by cDenius** [comment]
Maybe the best and cleanest approach would be to just measure three quibts and to assign a class to each qubit. The one closest to 1 gets the class vote. 

The problem could be that the circuit not only has to learn for each "classification qubit" to generate a high value in case of the respective class but also a low value for every other. In classical DL this is no problem because the neurons don't fire (= have a high output) if they are not triggered by what they have learnt. I'm not sure if this is the case for qubits.

**Comment by eileen-kuehn** [comment]
Another issue is that there might be more classes than qubits around. 
To keep it simple, let us first stick to selecting a subspace of states. All the other thoughts might be worthwhile to consider in the future.
