### ISSUE TITLE
Logging of testing leads to invalid json files. 

### ISSUE THREAD

**Issue by cDenius** [cirKITers/masKIT#60]
The json output file contains two root elements (one for train and one for testing) and is therefore not valid. For this reason, we can no longer use ```json.loads()``` to load the files (but there are [workarounds](https://stackoverflow.com/questions/21058935/python-json-loads-shows-valueerror-extra-data/51830719)).

I suggest to either create two output files (one for training, one for testing) or to integrate the testing values as an object into training. 

The solution should also take into account how the validation will/should be logged.

**Comment by eileen-kuehn** [comment]
This is a stream of json objects and is completely valid this way ;) Please have a look at [JSON Lines](https://jsonlines.org) for further information.

**Comment by eileen-kuehn** [comment]
> The solution should also take into account how the validation will/should be logged.

Could you please specify what you mean with this?

**Comment by cDenius** [comment]
> Could you please specify what you mean with this?

I guess the validation should be logged once it is implemented. If we change something about the current logging the solution should applicable for validation as well.

**Comment by cDenius** [comment]
> This is a stream of json objects and is completely valid this way ;) Please have a look at [JSON Lines](https://jsonlines.org) for further information.
> 
> However it might be, that we are missing the correct line separator. I will have a look later.

Hmm maybe invalid was the wrong term. If I understand your link and my link correctly, there are just multiple json objects in one file. In that case, I would suggest to follow the suggested conventions from your link:

> JSON Lines files may be saved with the file extension .jsonl
